### ISSUE TITLE
License Deactivated

### ISSUE THREAD

**Issue by islandoflotuseaters** [bid-sniper/shopgoodwill-bid-sniper#14]
My lifetime license randomly deactivated, was this maybe automated because you refunded my payment?

**Comment by bid-sniper** [comment]
Hi islandoflotuseaters,

Is there anything in particular that changed on your end that you think may have triggered this, for example, switching users or computers? Can you please confirm you are not using the old version by accident?

Best regards,
Tech Support

**Comment by islandoflotuseaters** [comment]
Nope, using the same computer, same user, and have launched directly from the Microsoft store to make sure that it's the current version. The only thing that happened is that suddenly auction pages and "My Favorites" page weren't loading correctly, so I logged out of my Goodwill account and logged back in, which fixed the loading issue, but now hitting the snipe button launches the license purchase window again.

**Comment by bid-sniper** [comment]
Oh ok so you logged out before the issue occurred... Ok that helps us narrow down the issue... We will look into this right away and get back to you with an update shortly!

**Comment by islandoflotuseaters** [comment]
Yeah, but because item pages wouldn't load until after I logged out and then logged back in, it's possible that whatever went wrong happened before and that's why it wouldn't load any item pages. Thank you for looking into it.

**Comment by bid-sniper** [comment]
Hi islandoflotuseaters,

Please update to the newest version on the App Store, and then use the following coupon code during checkout to activate:

Coupon Code: islandoflotuseaters

**Comment by islandoflotuseaters** [comment]
Perfect, thank you.
