### ISSUE TITLE
Lifetime license randomly deactivated again

### ISSUE THREAD

**Issue by islandoflotuseaters** [bid-sniper/shopgoodwill-bid-sniper#22]
My lifetime license randomly deactivated again

**Comment by bid-sniper** [comment]
Hi, please use the following coupon code to activate it again: islandoflotuseaters

**Comment by islandoflotuseaters** [comment]
Much appreciated, thank you.

**Comment by bid-sniper** [comment]
You're welcome, please let us know if we can be of further assistance, Thank You!
