### ISSUE TITLE
I bought 5 bids, only allowed one which did not execute.

### ISSUE THREAD

**Issue by sogoodonyou** [bid-sniper/shopgoodwill-bid-sniper#23]
Hi,

After buying 5 bids I sniped a bid on an item.  At the end of the auction there were no bids on the item, so I didn't get it.  Today I went to bid again and I get a repeated error and it keeps bringing up the purchase bid screen. 
![detroit tigers 1](https://github.com/bid-sniper/shopgoodwill-bid-sniper/assets/162194740/030bf93f-d833-4682-96f6-fdc248bc92d1)
<img width="700" alt="detroit tigers 3" src="https://github.com/bid-sniper/shopgoodwill-bid-sniper/assets/162194740/ea38742b-c7e8-4698-92b9-72183e96ceab">

Please fix or refund.  

Thanks!

**Comment by sogoodonyou** [comment]
Here's another screenshot of failed bid:
![detroit tigers 2](https://github.com/bid-sniper/shopgoodwill-bid-sniper/assets/162194740/72a629c8-d7c9-42d5-88c4-9f4a6d24395c)

**Comment by bid-sniper** [comment]
Hi, regarding the error what is the exact action you take that causes the error to produce so that we can reproduce it here? Also regarding the refund, we can refund your $4.99 what is the date you paid and your name?

**Comment by sogoodonyou** [comment]
I haven't had the error since I restarted my laptop.  It was popping up constantly.  But now every time I try to make a bid the pay window comes up even though I've paid for 5 bids.

**Comment by bid-sniper** [comment]
What is your name and the date you paid we will refund your $4.99 and then you can purchase another 5 snipes?

**Comment by sogoodonyou** [comment]
Valerie Broatch, the date was Saturday the 2nd.  I'm looking at my credit card and it says paypal pending...?  Maybe the payment is the problem.

**Comment by bid-sniper** [comment]
Ok, we have refunded your payment in the amount of $4.99 so you can purchase 5 more and try again...

**Comment by sogoodonyou** [comment]
Thanks, I'll give it a shot.

**Comment by bid-sniper** [comment]
Ok, we will also look into the error and resolve it next release.

**Comment by sogoodonyou** [comment]
Thanks so much
